server:
  port: 8081
  servlet:
    context-path: /user
spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

order-service:
  url: http://order-service/