server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/productService/**
          filters:
            - name: CircuitBreaker
              args:
                name: psFallback
                fallbackUri: forward:/productServiceFallback
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/userService/**
      default-filters:
        - name: CircuitBreaker
          args:
            name: globalFallback
            fallbackUri: forward:/defaultFallback

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true