server:
  port: 8082
  servlet:
    context-path: /service-b
spring:
  application:
    name: service-b
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
