server:
  port: 8081
  servlet:
    context-path: /service-a
spring:
  application:
    name: service-a
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
